### ISSUE TITLE
私自研究了下大佬的代码

### ISSUE THREAD

**Issue by zhyueyueniao** [NNNNolan/Ark#47]
私自研究了下大佬的代码，发现识别验证码使用的是旧版的OpenCvSharp，OpenCvSharp不支持arm，所以部署arm需要另外的项目，但是我发现OpenCvSharp的升级版OpenCvSharp4可以支持arm啊，更新为OpenCvSharp4就可以直接支持arm了
然后还有个问题，在Linux下无法写日志，应该是大佬加载log4net日志配置有点问题，没有使用Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "log4net.config")，导致获取不到log4net配置
最后，求大佬赏个授权码呗

**Comment by binggz** [comment]
还以为楼主研究出来啦，我也研究了下，能力之外，旧版先用着。等开放日

**Comment by zhyueyueniao** [comment]
> 研究出来了，只是有授权码还是用授权码吧，私自破解人家辛苦弄好的东西不好

**Comment by binggz** [comment]
> 

nolan大大也只是希望不滥用

**Comment by binggz** [comment]
序列号:c0fde8c9b4c49c2a2e28e4eff68c9e93
闲暇来逛，期待给个许可
